gui:
  showIcons: true
  showCommandLog: true
  commandLogSize: 80
  theme:
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - black
os:
  openCommand: "code -rg {{filename}}"
git:
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium --oneline {{branchName}} --"
