tap "jesseduffield/lazygit"
tap "homebrew/cask-fonts"
tap "FelixKratz/formulae"

brew "act"
brew "ansifilter"
brew "atuin"
brew "bat"
brew "colima"
brew "cowsay"
brew "ctop"
brew "exa"
brew "fzf"
brew "fd"
brew "gawk"
nrew "gh"
nrew "gh-dash"
brew "htop"
brew "jq"
brew "kubectl"
brew "jesseduffield/lazygit/lazygit"
brew "jesseduffield/lazydocker/lazydocker"
brew "lazygit"
brew "lazydocker"
brew "mas"
brew "mkcert"
brew "ncdu"
brew "neovim"
brew "nginx"
brew "openssl@1.1"
brew "overmind"
brew "ripgrep"
brew "rustup"
brew "stow"
brew "the_silver_searcher"
brew "tmux"
brew "zoxide"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "zsh"

cask "1password"
cask "alacritty"
cask "alfred"
cask "background-music"
cask "docker"
cask "dropbox"
cask "font-hack-nerd-font"
cask "google-chrome"
cask "guitar-pro"
cark "hammerspoon"
cask "insomnia"
cask "kitty"
cask "onyx"
cask "responsively"
cask "scroll-reverser"
cask "slack"
cask "spotify"
cask "tableplus"
cask "vlc"

mas "Monosnap", id: 540348655
mas "Spark", id: 1176895641

# Manual
## OniVim2 https://v2.onivim.io/early-access-portal
## Homerow https://www.homerow.app/
## gh TUI `gh extension install dlvhdr/gh-dash`
