# yaml-language-server: $schema=https://dlvhdr.github.io/gh-dash/configuration/gh-dash/schema.json
prSections:
  - title: Review
    filters: is:open review-requested:@me
  - title: Mine
    filters: is:open author:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
  - title: All
    filters: is:open
  - title: Past mine
    filters: is:closed author:@me
issuesSections:
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
pager:
  diff: "diffnav"
defaults:
  view: prs
  refetchIntervalMinutes: 5
  preview:
    open: true
    width: 100
  prsLimit: 20
  issuesLimit: 20
  layout:
    prs:
      updatedAt:
        width: 7
      repo:
        width: 20
      author:
        width: 15
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 16
    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: true
keybindings:
  issues: []
  prs: []
repoPaths: {}
theme:
  ui:
    sectionsShowCount: true
    table:
      compact: true
  colors:
    text:
      primary: "#d5c4a1"
      secondary: "#a8a8a8"
      inverted: "#202020"
      faint: "#626262"
      warning: "#e78a4e"
      success: "#a9b665"
    background:
      selected: "#303030"
    border:
      primary: "#4e4e4e"
      secondary: "#626262"
      faint: "#888888"
